### ISSUE TITLE
Make it compatible with deployer 6.1

### ISSUE THREAD

**Issue by cheindl** [sourcebroker/deployer-extended-database#1]
At the moment deployer-extended-database does not work with deployer 6.1 as it e.g. requires a "server" configuration instead of a "host" configuration.

**Comment by kszymukowicz** [comment]
At this moment "deployer-extended-database" supports Deployer 4.3.1 only (the last version that supports php 5.6) and I am fine with this because not all websites that I support have php 7 at hoster side. This situation looks better and better each day however.

Therefore I am going to wait and make "deployer-extended-database" compatibile with Deployer 7.0.

Or if you want it faster then you can make pull request for compatibility with Deployer 6.1 - if done well then I will integrate it for next "deployer-extended-database".

**Comment by raupie** [comment]
here for the same reason. +1 for the 6.1 update.

**Comment by kszymukowicz** [comment]
Frankly I have no time now and no big pressure because Deployer 4.3 is working with PHP 7.x.
Also there is no big feature that I miss in Deployer 6.x.

**Comment by kszymukowicz** [comment]
Version 9.0.0 is Deployer 6 compatible.
